[package]
name = "wasmer/js-service-worker"
version = "0.1.0"
description = "wasmer/js-service-worker js worker"
readme = "README.md"

[dependencies]
"wasmer/winter" = "^0.1.0"

[fs]
"/src" = "./src"

[[command]]
name = "script"
module = "wasmer/winter:wasmer-winter"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
env = ["JS_PATH=/src/index.js"]
main-args = ["/src/index.js"]
