[package]
name = "wasmer/js-service-worker-example"
version = "0.1.3"
description = "wasmer/js-service-worker js worker"
readme = "README.md"
repository = "https://github.com/wasmerio/js-service-worker-example"

[dependencies]
"wasmer/winterjs" = "*"

[fs]
"/src" = "./src"

[[command]]
name = "script"
module = "wasmer/winterjs:wasmer-winter"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
main-args = ["/src/index.js"]
