[package]
name = "wasmer/js-service-worker-example"
version = "0.1.2"
description = "Javascript Service worker example"
readme = "README.md"
repository = "https://github.com/wasmerio/js-service-worker-example"

[dependencies]
"wasmer/winterjs" = "^0.1.2"

[fs]
"/src" = "./src"

[[command]]
name = "script"
module = "wasmer/winterjs:wasmer-winter"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
env = ["JS_PATH=/src/index.js"]
main-args = ["/src/index.js"]
